mushroom-4/mushroom-be

src/main/java/nbc/mushroom/domain/auth/dto/request/UserRegisterReq.java
src/main/java/nbc/mushroom/domain/bid/entity/Bid.java
src/main/java/nbc/mushroom/domain/product/entity/Product.java

> ex. #이슈번호
close #10 
1. 회원가입 할 때 비밀번호 형식을 검증하도록
2. TimeStamped를 상속하고 있지 않은 Entity들 상속하도록 (Product, Bid)
3. Product가 기본으로 INSPECTING 으로 status값을 가지도록

[Bug] 프로젝트 초기 구조에서 빼먹은 부분들 수정

---

src/main/java/nbc/mushroom/domain/common/exception/ExceptionType.java
src/main/java/nbc/mushroom/domain/product/controller/ProductControllerV1.java
src/main/java/nbc/mushroom/domain/product/dto/response/SearchProductRes.java
src/main/java/nbc/mushroom/domain/product/dto/response/searchProductRes.java
src/main/java/nbc/mushroom/domain/product/repository/ProductRepositoryCustom.java
src/main/java/nbc/mushroom/domain/product/repository/ProductRepositoryImpl.java
src/main/java/nbc/mushroom/domain/product/service/ProductService.java
src/main/java/nbc/mushroom/domain/user/dto/response/UserRes.java
src/main/java/nbc/mushroom/domain/user/service/UserService.java

> close. #4 
> 유저/비유저 상관 없이 상품을 상세 조회 가능하도록 기능을 구현하였습니다.
> 상품 아이디 값으로만 상세 조회를 구현하였는데 세밀 작업 시 유저와 관리자 권한을 추가하면 어떨까 고민해보았습니다.

[Feature(product)] 상품 상세 조회 기능 구현 

---

src/main/java/nbc/mushroom/domain/common/exception/ExceptionType.java
src/main/java/nbc/mushroom/domain/product/controller/ProductAdminControllerV1.java
src/main/java/nbc/mushroom/domain/product/entity/Product.java
src/main/java/nbc/mushroom/domain/product/service/ProductAdminService.java

> close #9 
> 관리자가 판매자로부터 상품을 받아 검수가 승인처리 되었을 때 상품 status가 INSPECTING 에서 WAITING으로 바뀌도록 구현했습니다.
> 상품 쪽 기능을 구현하시는 다빈님이나 태은님 그리고 저 이렇게 예외처리 관련해서 어떤 예외를 만들지 미리 정해놨으면 좋겠습니다! 비슷한 예외가 이미 다빈님이 만들어두신 게 있는데, 저와 에러코드 네이밍이 같아서 추후 문제가 될 소지가 있다고 판단됩니다. 

[Feature(product)] 관리자 경매 물품 상태 WAITING으로 변경 기능 구현 

---

src/main/java/nbc/mushroom/domain/product/controller/ProductControllerV1.java
src/main/java/nbc/mushroom/domain/product/repository/ProductRepositoryCustom.java
src/main/java/nbc/mushroom/domain/product/repository/ProductRepositoryImpl.java
src/main/java/nbc/mushroom/domain/product/service/ProductService.java

> close #26
>상품 전체 조회 기능을 페이징 포함하여 구현하였습니다.
> 이를 토대로 키워드 검색 기능을 포함하여 구현할 예정 입니다.

[Feature(product)] 상품 전체 조회 기능 구현

---

src/main/java/nbc/mushroom/domain/common/exception/ExceptionType.java
src/main/java/nbc/mushroom/domain/product/controller/ProductControllerV1.java
src/main/java/nbc/mushroom/domain/product/dto/request/CreateProductReq.java
src/main/java/nbc/mushroom/domain/product/dto/request/PutProductReq.java
src/main/java/nbc/mushroom/domain/product/dto/response/ProductRes.java
src/main/java/nbc/mushroom/domain/product/entity/Product.java
src/main/java/nbc/mushroom/domain/product/repository/ProductRepositoryImpl.java
src/main/java/nbc/mushroom/domain/product/service/ProductService.java

> close #2 
>
상품 삭제 및 수정 기능 구현
공통 dto 이름 변경 , 엔터티에 softDelete 메서드 생성, #1 에서 수정하지 못한 것들 수정 
고민 1. 응답 dto 가 공통의 역할을 할 때, 여러 dto를 생성해야 하는가
고민 2. 이미지의 파일 이름을 데이터 베이스에 넣으면 이미지 관련 메서드를 건들이지 않아도 되지만, 링크로 받을 시 이미지 로직에 delete를 filename 을 매개변수로 받지않고, 링크로 수정해야한다.
고민 3. softdelete 인 상황에서 이미지까지 남겨두는 것이 맞는 선택인가?

[Feature(Product)] 상품 삭제 및 수정 기능 구현

---

src/main/java/nbc/mushroom/domain/auction_item/controller/AuctionItemControllerV1.java
src/main/java/nbc/mushroom/domain/auction_item/repository/AuctionItemRepositoryCustom.java
src/main/java/nbc/mushroom/domain/auction_item/repository/AuctionItemRepositoryImpl.java
src/main/java/nbc/mushroom/domain/auction_item/service/AuctionItemService.java

> close #5 close #44 
> 필터링과 정렬(페이징 포함)을 통한 만능 검색 기능 구현하였습니다.
> 좋아요(찜하기)를 정렬로 넣고자 고민하였는데, 로직이 복잡해질 것 같아 추가 구현으로 빼두었습니다.

[Feature(auction_item)] 경매 물품 키워드 + 정렬 조회 기능 구현

---

src/main/java/nbc/mushroom/domain/bid/repository/BidRepositoryCustom.java
src/main/java/nbc/mushroom/domain/bid/repository/BidRepositoryImpl.java
src/main/java/nbc/mushroom/domain/common/exception/ExceptionType.java
src/main/java/nbc/mushroom/domain/user/controller/UserBidControllerV1.java
src/main/java/nbc/mushroom/domain/user/service/UserBidService.java

> ex. #이슈번호
close #37 
> 무엇을 했는지 요약
- 유저의 입찰 목록 중 특정 입찰의 상세 내용을 조회할 수 있는 기능을 구현하였습니다.
#41 해결 후 merge 하겠습니다!
- Postman 실행 결과

[Feature(user, bid)] 입찰 내역 상세 조회 기능 구현

---

src/main/java/nbc/mushroom/domain/auction_item/repository/AuctionItemRepositoryImpl.java

> close #46 
> 누락한 쿼리문(where절 안 키워드 쿼리)을 추가하였습니다.
> NONE

[BUG(auction_item)] 경매 물품 키워드 검색 조회 오류 수정

---

src/main/java/nbc/mushroom/domain/auction_item/entity/AuctionItem.java
src/main/java/nbc/mushroom/domain/auction_item/repository/AuctionItemRepositoryImpl.java
src/main/java/nbc/mushroom/domain/bid/service/BidService.java

> close #51 
> 곳곳에 api response가 아니라 exception type으로 반환되고 있는 에러 메시지들을 static 형태로 통일 시켰습니다.
> 미처 고치지 못한 부분이나, 틀리게 수정된 부분이 있을 수도 있으니 다시 한 번 훑어주세요! 

[Refactor(ALL)] Error Response를 static 으로 통일

---

src/main/java/nbc/mushroom/domain/bid/service/BidService.java

> ex. #이슈번호
close #49 
> 무엇을 했는지 요약
- 본인의 경매 물품을 입찰할 수 있는 버그를 해결하였습니다.
유저1 (id=1)가 경매 물품 등록
유저1 (id=1)가 본인의 경매 물품 입찰을 시도 

[Bug(bid)] 입찰 시 자신의 경매 물품도 참여 가능한 오류 수정

---

src/main/java/nbc/mushroom/domain/auction_item/repository/AuctionItemRepositoryImpl.java
src/main/java/nbc/mushroom/domain/auction_item/service/AuctionItemStatusService.java
src/main/java/nbc/mushroom/domain/bid/entity/Bid.java
src/main/java/nbc/mushroom/domain/bid/entity/BiddingStatus.java
src/main/java/nbc/mushroom/domain/bid/repository/BidRepositoryCustom.java
src/main/java/nbc/mushroom/domain/bid/repository/BidRepositoryImpl.java
src/main/java/nbc/mushroom/domain/bid/service/BidService.java
src/main/java/nbc/mushroom/domain/common/exception/ExceptionType.java
src/main/java/nbc/mushroom/domain/user/controller/UserBidControllerV1.java
src/main/java/nbc/mushroom/domain/user/service/UserBidService.java

> ex. #이슈번호
close #55 
> 무엇을 했는지 요약
- 입찰을 취소할 수 있도록 기능을 구현했습니다.
- 경매 종료 24시간 이내로는 취소 불가
- 입찰 취소 내역이 총 3회가 넘어갈 시 취소 불가
- 입찰이 진행 중인 상태가 아니면 취소 불가
- PR 주제와 어울리지는 않지만 직전에 PR했던 유저 검증 로직이 중복된 것을 발견했습니다. 빠른 수정을 위해 같이 PR 올립니다. 
- 외에도 ExceptionType을 정적 import로 바꿨습니다. 이것 또한 빠른 반영을 위해 같이 PR 올립니다. 

[Feature(bid)] 입찰 취소 기능 구현

---

src/main/java/nbc/mushroom/domain/auction_item/repository/AuctionItemRepositoryImpl.java

> close #63 
> 무엇을 했는지 요약
복합 인덱스 적용 가능하도록 쿼리문을 수정하였습니다.
NONE

[BUG(auction_item)] 키워드 전체 조회 기능에서 복합 인덱스 쿼리문 수정

---

src/main/java/nbc/mushroom/domain/auction_item/controller/AuctionItemControllerV2.java
src/main/java/nbc/mushroom/domain/auction_item/dto/response/AuctionItemBidInfo.java
src/main/java/nbc/mushroom/domain/auction_item/dto/response/AuctionItemBidInfoRes.java
src/main/java/nbc/mushroom/domain/auction_item/dto/response/SearchAuctionItemBidRes.java
src/main/java/nbc/mushroom/domain/auction_item/service/AuctionItemService.java
src/main/java/nbc/mushroom/domain/bid/repository/BidRepositoryCustom.java
src/main/java/nbc/mushroom/domain/bid/repository/BidRepositoryImpl.java

> close #60 
> 기존에 목록 조회 api 에 bid 정보가 있다면, 현재 경매 물품 최고 입찰가와 닉네임을 같이 반환한다.
> 서브 쿼리로 한번에 날리기, 쿼리를 여러번 보내기, 레포지토리에서 받은 객체를 service 단에서 처리 후 응답 객체 생성하기

[Feature(auction_item)] 경매 물품 상세 조회 V2

---

src/main/java/nbc/mushroom/domain/auction_item/repository/AuctionItemRepositoryImpl.java

> close #62 
> Boolean Expression -> Boolean Builder 로 로직 구현 수정하였습니다(5분 기록 보드 참고).
> 제가 만든 로직이 Impl에서만 쓰이는 관계로 접근제어자를 private로 생성한 뒤 public과 섞이지 않게 밑으로 빼내었습니다.

[BUG(auction_item)] 키워드 전체 조회 로직 구현을 Boolean Builder로 수정 완료

---

src/main/java/nbc/mushroom/domain/like/repository/LikeRepositoryCustom.java
src/main/java/nbc/mushroom/domain/like/repository/LikeRepositoryImpl.java
src/main/java/nbc/mushroom/domain/user/controller/UserAuctionItemLikeControllerV2.java
src/main/java/nbc/mushroom/domain/user/dto/response/SearchUserAuctionItemLikeRes.java
src/main/java/nbc/mushroom/domain/user/service/UserAuctionItemLikeService.java

> ex. #이슈번호
close #58 
> 무엇을 했는지 요약
좋아요 를 id 오름차순으로 페이징 조회 
- 필드는 개인적 주관으로 필요하다고 생각되는 것만 넣음 - 이것은 말씀해주시면 바꿀 예정
- 경매 물품의 상태는 고려하지 않음 - 완료 상태인 것도 좋아요 를 남겨야 해당 좋아요 를 삭제할 수 있어서, 경매 물품 상태로 조건은 걸지 않음

[Feature(user)] 사용자 본인이 좋아요 한 경매 물품 조회 구현

---

src/main/java/nbc/mushroom/domain/like/repository/LikeRepositoryCustom.java
src/main/java/nbc/mushroom/domain/like/repository/LikeRepositoryImpl.java
src/main/java/nbc/mushroom/domain/notice/dto/NoticeRes.java
src/main/java/nbc/mushroom/domain/notice/dto/SearchNoticeRes.java
src/main/java/nbc/mushroom/domain/notice/dto/SearchPageNoticeRes.java
src/main/java/nbc/mushroom/domain/notice/entity/Notice.java
src/main/java/nbc/mushroom/domain/notice/entity/NoticeType.java
src/main/java/nbc/mushroom/domain/notice/repository/NoticeRepository.java
src/main/java/nbc/mushroom/domain/notice/repository/NoticeRepositoryCustom.java
src/main/java/nbc/mushroom/domain/notice/repository/NoticeRepositoryImpl.java
src/main/java/nbc/mushroom/domain/notice/service/NoticeService.java
src/main/java/nbc/mushroom/domain/user/controller/UserNoticeController.java
src/main/java/nbc/mushroom/domain/user/controller/UserNoticeControllerV2.java
src/main/java/nbc/mushroom/domain/user/service/UserNoticeService.java

> ex. #이슈번호
close #59 
> 무엇을 했는지 요약
notice 를 스케줄러로 생성
유저의 notice 조회
notice 에 like 가 필요한 지가 대해 너무 고민 됩니다! - 튜터님께서는 당장에는 필요 없어 보인다고 말씀하시는데.. 
조회할 때, 서비스 단에서 그들을 재 조합해서 페이징이 서비스 단에 있습니다.
조회할 때, notice가 종료를 기반으로 만들어 졌을 때, 종료 10분 전에 최고 입찰가를  도전 중에 있습니다. - 매우 복잡...

[Feature(user)] notice 생성 및 notice 조회

---

src/main/java/nbc/mushroom/domain/bid/repository/BidRepositoryImpl.java
src/main/java/nbc/mushroom/domain/like/repository/LikeRepositoryCustom.java
src/main/java/nbc/mushroom/domain/like/repository/LikeRepositoryImpl.java
src/main/java/nbc/mushroom/domain/notice/dto/NoticeRes.java
src/main/java/nbc/mushroom/domain/notice/dto/SearchNoticeRes.java
src/main/java/nbc/mushroom/domain/notice/dto/SearchPageNoticeRes.java
src/main/java/nbc/mushroom/domain/notice/entity/Notice.java
src/main/java/nbc/mushroom/domain/notice/entity/NoticeType.java
src/main/java/nbc/mushroom/domain/notice/repository/NoticeRepository.java
src/main/java/nbc/mushroom/domain/notice/repository/NoticeRepositoryCustom.java
src/main/java/nbc/mushroom/domain/notice/repository/NoticeRepositoryImpl.java
src/main/java/nbc/mushroom/domain/notice/service/NoticeService.java
src/main/java/nbc/mushroom/domain/user/controller/UserNoticeController.java
src/main/java/nbc/mushroom/domain/user/controller/UserNoticeControllerV2.java
src/main/java/nbc/mushroom/domain/user/service/UserNoticeService.java

> ex. #이슈번호
close #81 
> 무엇을 했는지 요약
잘못된 코드를 수정
감사합니다. 제가 잘 확인을 잘못했네요
그리고 커밋 내용이 많은데 섞인거 같습니다 마지막 커밋 내용만 보시며 됩니다.

BUG(auction_item)] 경매 물품 상세 v2 잘못된 값 반환

---

src/main/java/nbc/mushroom/config/websocket/RedisChatConfig.java
src/main/java/nbc/mushroom/config/websocket/StompHandler.java
src/main/java/nbc/mushroom/domain/chat/dto/response/ChatMessageRes.java
src/main/java/nbc/mushroom/domain/chat/event/ChatEventListener.java
src/main/java/nbc/mushroom/domain/chat/service/ChatService.java
src/main/java/nbc/mushroom/domain/chat/service/RedisPublish.java
src/main/java/nbc/mushroom/domain/chat/service/RedisSubscriber.java
src/main/resources/static/index.html

> ex. #이슈번호
close #89 
> 무엇을 했는지 요약
- 연결을 새로 하면(새로고침, 중간에 들어오기 등) 이전 채팅 내용이 불러와지도록 구현 했습니다.
-  유저가 새로 입장할 때마다 이전 채팅 내역이 불러와집니다.. 
- 급한 불부터 꺼야 하기 때문에 중간 시연 후 고치도록 하겠습니다!
- 해당 PR 병합 후, 최고입찰가를 메시지로 보내주는 브랜치 PR 올리겠습니다. 

[Feature(chat)] 이전 채팅 내용 조회 구현

---

src/main/java/nbc/mushroom/config/CacheConfig.java
src/main/java/nbc/mushroom/domain/admin/controller/AuctionItemAdminControllerV1.java
src/main/java/nbc/mushroom/domain/auction_item/service/AuctionItemStatusService.java
src/main/java/nbc/mushroom/domain/notice/service/NoticeService.java
src/main/resources/application-test.yml

> NONE
> CaffeineCacheManager를 RedisCacheManager로 변경해 레디스를 사용하도록 변경했습니다. 테스트를 위해 주석처리 해놨던 로컬 메모리 캐시 사용 로직을 삭제하고, 비활성화 해놨던 Scheduled를 활성화 해 커밋했습니다. 그 외 자잘한 주석 수정, 삭제가 있었습니다. 또한 사용하지 않는 product 디렉토리를 삭제했습니다. 
> NONE

[Feature(auction_items)] 인기 검색어 캐싱을 로컬 메모리에서 레디스 캐싱으로 변경

---

src/main/java/nbc/mushroom/domain/notice/dto/ReadNoticeRes.java
src/main/java/nbc/mushroom/domain/notice/service/NoticeCreateService.java
src/main/java/nbc/mushroom/domain/notice/service/NoticeReadService.java

> close #105 
https://github.com/user-attachments/assets/fc38b1bc-3928-4805-81a6-7250370a7674
위의 영상처럼 눌렀을 때 넘어갈 수 있도록 auctionItemId가 필요해서 추가했습니다.

[Feature(notice)] 공지 반환값으로 auctionItemId 추가 반환
